name: Validate Commit
on:
  push:
    branches: [main]
jobs:
  validate:
    name: Validate Commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Tome Librarian CLI
        run: |
          curl -sL https://github.com/tome-gg/librarian/releases/download/0.4.4/tome-linux-amd64 -o tome
          chmod +x tome
          sudo mv tome /usr/local/bin/tome

      - name: Run Tome Librarian CLI
        id: run-tome-librarian-cli
        run: tome validate .

      - name: Set Status
        if: ${{ success() }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: "Valid Tome.gg repository"

      - name: Set Status
        if: ${{ failure() }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: "Invalid Tome.gg repository: ${{ steps.run-tome-librarian-cli.outputs.stderr }}"
